language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: HbxSTt0QCSNN3IWSmru0CwhPQplAQecGPlD+SDw6nlosKtHTccNi+0JmDoY2qrKEM9GZQyt4GM+7DmsMMDEYM/jkXjAgkXN/whVpSgUSPNz0krOJ0KJzz1Qdho1H0CvfwCVWWR9JaEZa5m9J+fDMc4a11zTYfab9izLjqK8YZCVk7fk/LwfpcnCEZO8jGs4pn/niMq7zXmW1AydfZDuJf3w84kioeTO8ioNCQFO6gJ6SNdpnPGOrV2c6mIfw0464IuDu+pChTmQYnxtenMBgqEJJK9orO9OM+zkUVjgJ0qGprl751H+79FJdvakmra1xn3o9mGH2afM+va7Inke0jMdRLTI9J9Pnyb0dooh9h0cNFDrPaAEOslK15C1v7YFbPeZda4kn9FA/qzCQ6rhABdSbBogEpKSmTpUh81qWz6kFxrYtHPkkoQ6MIN4f7C5suBEKZ0ytLrTei4AUa8p3rxfTTCIw1uxY6Gi5PT/3JvwdWyZXZ5P81QuuHhzIt4Gg7/ONfG6gfYzDI6am9cQHvnyhj4deQo8iOLzUZEqZgpTdOsvT6x/K0HXixR8mAnhZ08cyaimX2WnozRiHRh0YTskWgvwCNzv9lm1l82md3L+5ySZsqaFZPbsZTbWCnFGTzNKoLGrHAouy/u5htCSgKvfy2fzzSomTtYYO1UOPDB0=
  app: vote-local-fe
  on:
    repo: vote-local/vote_local_fe
    branch: main
  cleanup: 'true'
