language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure:
  app:
  run: rails db:migrate
